#!/bin/sh

SITE="http://ftp.cc.monash.edu.au/pub/nihongo"

for docfile in {{e{nam,}dict,kanjidic}_doc,engscidich}.{html,txt} \
               j_places.inf {4jwords,compverb}.doc; do
    
    wget  "$SITE"/"$docfile" -O"$docfile".new && mv -f "$docfile".new "$docfile"

done

for gzfile in edict enamdict kanjidic engscidic j_places geodic compverb 4jwords; do

    wget "$SITE"/"$gzfile".gz -O"$gzfile".new && gzip -d < "$gzfile".new > "$gzfile" && rm -f "$gzfile".new

done

for zipfile in classical ediclsd3 lawgledt stardict aviation \
               {comp,geo,ling,fin,mkt,pandp}dic concrete; do

    wget -c "$SITE"/"$zipfile".zip -O"$zipfile".zip.new

done

for s in aviation classical compdic concrete ediclsd3 findic \
         geodic lawgledt mktdic pandpdic; do

  unzip -o "$s".zip.new "$s" '*.txt' '*.html' '*.euc' '*.doc' '*.inf' \
     && rm -f "$s".zip.new

done

#Copyrights of zip-files:
# Aviation: Feel free to do anything, just don't charge anybody else for it.
# Classical: Can be used, with acknowledgement, for any free software or server.
# Compdic: edict_license.html
# Concrete: Please include the readme and happy to receive email.
# Ediclsd3: Free for personal, but public or commercial util need a written permission.
# Findic: Unknown
# Geodic: Unknown
# Lawgledt: Distributable, but not to be sold.
# Lingdic: Distributable, but not to be sold. Publishing on paper needs a written permission.
# Mktdic: Unknown
# Pandpgls: Unknown
# Stardict: Unknown

#Other:
# 4jwords: Unknown
# Compverb: Unknown (btw this is a subset of Edict)
# Edict: edict_license.html
# Enamdict: edict_license.html
# Engscidich: Unknown
# J_places: Unknown
# Kanjidic: edict_license.html
